export enum FuelTypeEnum {
  GASOLINE = 'GASOLINE',
  DIESEL = 'DIESEL',
  ELECTRIC = 'ELECTRIC',
  HYDROGEN = 'HYDROGEN',
  GAS = 'GAS',
  ETHANOL = 'ETHANOL',
  BIOFUEL = 'BIOFUEL',
  OTHER = 'OTHER'
}
