services:
  postgres:
    image: postgres:16.3-alpine
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - boilerplate-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  maildev:
    image: maildev/maildev:latest
    restart: always
    environment:
      - MAIL_PORT=1025
      - MAIL_CLIENT_PORT=1080
    ports:
      - "1025:1025"  # SMTP port
      - "1080:1080"  # Web interface port

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
  # Uncomment to use redis
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - 6379:6379

#  api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - ${APP_PORT}:${APP_PORT}

volumes:
  boilerplate-db:
