export enum InvoiceStatusEnum {
  ISSUED = 'ISSUED',
  RECEIVED_WITHOUT_OBSERVATIONS = 'RECEIVED_WITHOUT_OBSERVATIONS',
  RECEIVED_WITH_OBSERVATIONS = 'RECEIVED_WITH_OBSERVATIONS',
  PAID = 'PAID',
  REJECTED = 'REJECTED',
  RE_INVOICED = 'RE_INVOICED',
}
